[Test Game.game]
    Emulator= "PC"
    Enabled= True
    Alias= ""
    Description= ""
    Icon_Location= "./Games"
    Banner_Location= "./Games"
    Game_Location= "./Games"
    Save_location= "./Games"
    Game_Type= ".game"
    Save_Type= ".sav"
    Args= []
    Manual_Start_Cmd= ""
    Release_Dates= {"USA":"January 1st, 2000",}
    Popularity= "10/10"
    Genres= []
    Languages= ["English",]
    Developer= []
    Publishers= []
    Players= "1-4"
    Connectivity= ""
    Series= ""
    Rating= {"ESRB":"E"}
    Ext_Link= ""
